### ISSUE TITLE
"Looks like something broke. Try again? (yes/no)"

### ISSUE THREAD

**Issue by meliache** [gcr/tumblesocks#12]
I am Emacs 24 on Debian Jessie (the current "testing"). 
Here is my output from <M-x version>: "GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.8.4) of 2013-09-27 on trouble, modified by Debian".

I installed tumblesocks with marmalade which, to be honest, I just installed. It said that 6 files were compiled and one skipped. Okay... 

I continued by adding 

(require 'tumblesocks)
(setq tumblesocks-blog "MyBlogName.tumblr.com") 

to my .emacs and restarted it and there were no complains. However, when I do "M-x tumblesocks-api-test-auth" it always returns

" Looks like something broke. Try again? (yes/no) (yes or no) "
That doesn't help me much. Typing "yes" doesn't do anything.

 I still have only very little experience with programming and know only some basics of emacs lisp. I have no idea what the fault might be so I felt like there was no other possibility than contacting you.
## The following is the compile log that I got from my installation with marmalade:

Leaving directory `/home/michael/.emacs.d/elpa/tumblesocks-0.0.6'

Compiling file /home/michael/.emacs.d/elpa/tumblesocks-0.0.6/tumblesocks-api.el at Mon Nov  4 00:14:55 2013
Entering directory`/home/michael/.emacs.d/elpa/tumblesocks-0.0.6/'

In tumblesocks-api-http-oauth-get:
tumblesocks-api.el:135:51:Warning: (lambda (x) ...) quoted with ' rather than
    with #'

In tumblesocks-api-http-apikey-get:
tumblesocks-api.el:150:49:Warning: (lambda (x) ...) quoted with ' rather than
    with #'

In tumblesocks-api-http-oauth-post:
tumblesocks-api.el:168:28:Warning: (lambda (x) ...) quoted with ' rather than
    with #'

Compiling file /home/michael/.emacs.d/elpa/tumblesocks-0.0.6/tumblesocks-compose.el at Mon Nov  4 00:14:55 2013

Compiling file /home/michael/.emacs.d/elpa/tumblesocks-0.0.6/tumblesocks-pkg.el at Mon Nov  4 00:14:55 2013

Compiling file /home/michael/.emacs.d/elpa/tumblesocks-0.0.6/tumblesocks-user.el at Mon Nov  4 00:14:55 2013

In tumblesocks-unfollow-blog:
tumblesocks-user.el:47:33:Warning: (lambda (blog) ...) quoted with ' rather
    than with #'

Compiling file /home/michael/.emacs.d/elpa/tumblesocks-0.0.6/tumblesocks-view.el at Mon Nov  4 00:14:56 2013

In tumblesocks-view-previous-post:
tumblesocks-view.el:75:5:Warning: `previous-line' used from Lisp code
That command is designed for interactive use only

In tumblesocks-view-next-post:
tumblesocks-view.el:91:5:Warning: `next-line' used from Lisp code
That command is designed for interactive use only

In tumblesocks-view-insert-parsed-html-fragment:
tumblesocks-view.el:203:9:Warning: `flet' is an obsolete macro (as of 24.3);
    use either`cl-flet' or `cl-letf'.

In tumblesocks-view-previous-page:
tumblesocks-view.el:248:4:Warning: `previous-line' used from Lisp code
That command is designed for interactive use only

In tumblesocks-view-insert-header:
tumblesocks-view.el:338:13:Warning: reference to free variable `blog_name'
tumblesocks-view.el:343:7:Warning: reference to free variable`title'
tumblesocks-view.el:344:54:Warning: reference to free variable `caption'
tumblesocks-view.el:345:55:Warning: reference to free variable`question'
tumblesocks-view.el:348:30:Warning: reference to free variable `note_count'
tumblesocks-view.el:351:11:Warning: reference to free variable`liked'
tumblesocks-view.el:356:17:Warning: reference to free variable `date'
tumblesocks-view.el:356:17:Warning: (lambda (x) ...) quoted with ' rather than
    with #'
tumblesocks-view.el:357:59:Warning: reference to free variable`tags'
tumblesocks-view.el:360:22:Warning: reference to free variable `post_url'

In tumblesocks-view-insert-text:
tumblesocks-view.el:371:42:Warning: reference to free variable `body'

In tumblesocks-view-insert-photo:
tumblesocks-view.el:377:23:Warning: (lambda (photodata) ...) quoted with '
    rather than with #'
tumblesocks-view.el:386:35:Warning: (lambda (alt) ...) quoted with ' rather
    than with #'
tumblesocks-view.el:396:23:Warning: reference to free variable `photos'
tumblesocks-view.el:398:11:Warning: reference to free variable`caption'

In tumblesocks-view-insert-quote:
tumblesocks-view.el:403:42:Warning: reference to free variable `text'
tumblesocks-view.el:405:42:Warning: reference to free variable`source'

In tumblesocks-view-insert-answer:
tumblesocks-view.el:409:11:Warning: reference to free variable `asking_name'
tumblesocks-view.el:412:44:Warning: reference to free variable`question'
tumblesocks-view.el:414:42:Warning: reference to free variable `answer'

In tumblesocks-view-insert-link:
tumblesocks-view.el:417:63:Warning: reference to free variable `url'
tumblesocks-view.el:419:42:Warning: reference to free variable`description'

In tumblesocks-view-insert-chat:
tumblesocks-view.el:423:20:Warning: reference to free variable `dialogue'

In tumblesocks-view-insert-i-have-no-clue-what-this-is:
tumblesocks-view.el:433:39:Warning: reference to free variable `type'

In tumblesocks-view-render-notes:
tumblesocks-view.el:545:10:Warning: `flet' is an obsolete macro (as of 24.3);
    use either`cl-flet' or `cl-letf'.

Compiling file /home/michael/.emacs.d/elpa/tumblesocks-0.0.6/tumblesocks.el at Mon Nov  4 00:14:56 2013

**Comment by tariqk** [comment]
I'm currently using the following version of emacs:

    GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-09-18

I'm still receiving this error, despite running running `M-: (setq oauth-nonce-function 'oauth-internal-make-nonce)`:

```
Looks like something broke. Try again? (yes/no) (y or n)
```

Running `M-: (setq debug-on-error)` doesn't change the error message. Running `M-: (browse-url "http://www.google.com/")` loads Firefox to Google, as expected.

Is there anything I can do to find out more at what's happening?
