### ISSUE TITLE
tumblesocks not inserting images by default

### ISSUE THREAD

**Issue by rrix** [gcr/tumblesocks#17]
Spent about an hour spelunking shr.el trying to figure out why this is the case, but I have to manually insert each image, which makes browsing a bit of a PITA.

![](http://i.imgur.com/LM6YccA.gif)

**Comment by gcr** [comment]
Oh interesting! How are you manually inserting the images? What platform are you on?

Images show up as an asterisk until they've been downloaded, which should happen asynchronously. (e.g. for me, the *s change to images after a second or two).

**Comment by rrix** [comment]
Interestingly enough, the images are autoloading now that I've restarted my daemon. This was emacs24.5 on fedora. Not sure how to go about breaking it again ¯\_(ツ)_/¯

**Comment by gcr** [comment]
Strange... glad it's working! I wish shr.el had more robust asynchronous support.
